version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: permissionsapi_sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "14335:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: permissionsapi_api
  #   depends_on:
  #     - sqlserver
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PermissionsDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
  #   ports:
  #     - "5106:8080"
  #     - "5107:443"
  #   restart: unless-stopped

volumes:
  sqlserver_data: 